version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hands-on-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imobiliaria
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
